use_frameworks!

platform :ios, '10.0'

target 'VisualEffectBlurView_Example' do
  pod 'VisualEffectBlurView', :path => '../'

  target 'VisualEffectBlurView_Tests' do
    inherit! :search_paths

    
  end
end
